import type { YogaClass, Booking, Upsell, ReferralCode } from '@/types';
import { subDays, format } from 'date-fns';

// Colores por tipo de clase
export const CLASS_COLORS: Record<string, string> = {
  'Sunrise Vinyasa':        '#4a7c59',
  'Gentle Flow':            '#6baed6',
  'Ashtanga Primary':       '#c4622d',
  'Yin Yoga':               '#8b6bb8',
  'Power Flow':             '#e07b39',
  'Hatha Foundations':      '#5b9e6d',
  'Pranayama & Meditación': '#7ea8be',
  'Restorative Yoga':       '#b8860b',
  'Breath & Movement':      '#6b8a7a',
};

export const MOCK_CLASSES: YogaClass[] = [
  {
    id: 'cls-001',
    name: 'Sunrise Vinyasa',
    slug: 'sunrise-vinyasa',
    description: 'Despierta el cuerpo con una secuencia dinámica que conecta la respiración con el movimiento. Ideal para comenzar el día con energía y claridad mental.',
    instructor: 'Maya',
    startsAt: new Date('2026-05-04T06:30:00'),
    durationMinutes: 60,
    capacity: 12,
    spotsRemaining: 8,
    priceUsd: 25,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Sunrise Vinyasa'],
  },
  {
    id: 'cls-002',
    name: 'Gentle Flow',
    slug: 'gentle-flow',
    description: 'Una práctica suave y accesible para todos los niveles. Movimientos fluidos, posturas restaurativas y respiración consciente. Clase gratuita para huéspedes del hotel.',
    instructor: 'Sara',
    startsAt: new Date('2026-05-04T09:00:00'),
    durationMinutes: 75,
    capacity: 15,
    spotsRemaining: 12,
    priceUsd: 0,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Gentle Flow'],
  },
  {
    id: 'cls-003',
    name: 'Ashtanga Primary',
    slug: 'ashtanga-primary',
    description: 'La serie primaria de Ashtanga: una secuencia fija y exigente que purifica el cuerpo a través del movimiento, la respiración y la mirada. Para practicantes con experiencia.',
    instructor: 'Ravi',
    startsAt: new Date('2026-05-05T06:30:00'),
    durationMinutes: 90,
    capacity: 8,
    spotsRemaining: 4,
    priceUsd: 30,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Ashtanga Primary'],
  },
  {
    id: 'cls-004',
    name: 'Yin Yoga',
    slug: 'yin-yoga',
    description: 'Posturas pasivas sostenidas durante 3-5 minutos que trabajan en profundidad los tejidos conectivos. Profunda relajación y liberación de tensiones acumuladas.',
    instructor: 'Maya',
    startsAt: new Date('2026-05-05T09:00:00'),
    durationMinutes: 60,
    capacity: 10,
    spotsRemaining: 6,
    priceUsd: 25,
    location: 'Sala Interior',
    isActive: true,
    color: CLASS_COLORS['Yin Yoga'],
  },
  {
    id: 'cls-005',
    name: 'Power Flow',
    slug: 'power-flow',
    description: 'Vinyasa de alta intensidad que desarrolla fuerza, flexibilidad y resistencia. Espera transiciones fluidas y música que te mantiene en movimiento.',
    instructor: 'Ravi',
    startsAt: new Date('2026-05-06T06:30:00'),
    durationMinutes: 60,
    capacity: 12,
    spotsRemaining: 9,
    priceUsd: 25,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Power Flow'],
  },
  {
    id: 'cls-006',
    name: 'Hatha Foundations',
    slug: 'hatha-foundations',
    description: 'Los pilares del yoga tradicional: asanas, pranayama y relajación profunda. Perfecta para principiantes o quienes buscan consolidar su práctica.',
    instructor: 'Sara',
    startsAt: new Date('2026-05-06T09:00:00'),
    durationMinutes: 75,
    capacity: 15,
    spotsRemaining: 11,
    priceUsd: 20,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Hatha Foundations'],
  },
  {
    id: 'cls-007',
    name: 'Pranayama & Meditación',
    slug: 'pranayama-meditacion',
    description: 'Una hora dedicada exclusivamente a técnicas de respiración y meditación guiada. Reducción del estrés, claridad mental y paz interior.',
    instructor: 'Maya',
    startsAt: new Date('2026-05-07T06:30:00'),
    durationMinutes: 60,
    capacity: 10,
    spotsRemaining: 0,
    priceUsd: 15,
    location: 'Sala Interior',
    isActive: true,
    color: CLASS_COLORS['Pranayama & Meditación'],
  },
  {
    id: 'cls-008',
    name: 'Restorative Yoga',
    slug: 'restorative-yoga',
    description: 'Profunda relajación con props (bolsters, mantas, bloques). El cuerpo se rinde completamente mientras la mente encuentra quietud.',
    instructor: 'Sara',
    startsAt: new Date('2026-05-07T09:00:00'),
    durationMinutes: 90,
    capacity: 12,
    spotsRemaining: 7,
    priceUsd: 25,
    location: 'Sala Interior',
    isActive: true,
    color: CLASS_COLORS['Restorative Yoga'],
  },
  {
    id: 'cls-009',
    name: 'Sunrise Vinyasa',
    slug: 'sunrise-vinyasa',
    description: 'Despierta el cuerpo con una secuencia dinámica que conecta la respiración con el movimiento.',
    instructor: 'Ravi',
    startsAt: new Date('2026-05-08T06:30:00'),
    durationMinutes: 60,
    capacity: 12,
    spotsRemaining: 5,
    priceUsd: 25,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Sunrise Vinyasa'],
  },
  {
    id: 'cls-010',
    name: 'Breath & Movement',
    slug: 'breath-and-movement',
    description: 'Fusión de pranayama consciente con movimiento intuitivo. Una práctica meditativa que integra cuerpo y mente a través del ritmo de la respiración.',
    instructor: 'Maya',
    startsAt: new Date('2026-05-08T09:00:00'),
    durationMinutes: 60,
    capacity: 10,
    spotsRemaining: 8,
    priceUsd: 20,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Breath & Movement'],
  },
  {
    id: 'cls-011',
    name: 'Sunrise Vinyasa',
    slug: 'sunrise-vinyasa',
    description: 'Despierta el cuerpo con una secuencia dinámica que conecta la respiración con el movimiento.',
    instructor: 'Maya',
    startsAt: new Date('2026-05-11T06:30:00'),
    durationMinutes: 60,
    capacity: 12,
    spotsRemaining: 12,
    priceUsd: 25,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Sunrise Vinyasa'],
  },
  {
    id: 'cls-012',
    name: 'Gentle Flow',
    slug: 'gentle-flow',
    description: 'Una práctica suave y accesible para todos los niveles. Clase gratuita para huéspedes del hotel.',
    instructor: 'Sara',
    startsAt: new Date('2026-05-11T09:00:00'),
    durationMinutes: 75,
    capacity: 15,
    spotsRemaining: 15,
    priceUsd: 0,
    location: 'Open-Air Shala',
    isActive: true,
    color: CLASS_COLORS['Gentle Flow'],
  },
  {
    id: 'cls-013',
    name: 'Ashtanga Primary',
    slug: 'ashtanga-primary',
    description: 'La serie primaria de Ashtanga. Para practicantes con experiencia.',
    instructor: 'Ravi',
    startsAt: new Date('2026-05-12T06:30:00'),
    durationMinutes: 90,
    capacity: 8,
    spotsRemaining: 2,
    priceUsd: 30,
    location: 'Open-Air Shala',
    isActive: false,
    color: CLASS_COLORS['Ashtanga Primary'],
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    classId: 'cls-001',
    className: 'Sunrise Vinyasa',
    firstName: 'Laura',
    lastName: 'Méndez',
    email: 'laura.mendez@email.com',
    phone: '+1 555-0101',
    persons: 1,
    upsells: ['ups-001'],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260504-A1B2',
    referralCode: 'SURF-CAMP',
    createdAt: new Date('2026-04-28T14:23:00'),
  },
  {
    id: 'bk-002',
    classId: 'cls-001',
    className: 'Sunrise Vinyasa',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@email.com',
    persons: 2,
    upsells: [],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260504-C3D4',
    createdAt: new Date('2026-04-29T09:11:00'),
  },
  {
    id: 'bk-003',
    classId: 'cls-002',
    className: 'Gentle Flow',
    firstName: 'Sofía',
    lastName: 'Ramírez',
    email: 'sofia.ramirez@email.com',
    phone: '+506 8888-1234',
    persons: 1,
    upsells: ['ups-002'],
    paymentStatus: 'free',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260504-E5F6',
    createdAt: new Date('2026-04-30T18:45:00'),
  },
  {
    id: 'bk-004',
    classId: 'cls-003',
    className: 'Ashtanga Primary',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'm.chen@email.com',
    persons: 1,
    upsells: [],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260505-G7H8',
    createdAt: new Date('2026-04-28T10:00:00'),
  },
  {
    id: 'bk-005',
    classId: 'cls-007',
    className: 'Pranayama & Meditación',
    firstName: 'Ana',
    lastName: 'Torres',
    email: 'ana.torres@email.com',
    phone: '+34 600-123-456',
    persons: 1,
    upsells: ['ups-001', 'ups-003'],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260507-I9J0',
    referralCode: 'INSTAGRAM',
    createdAt: new Date('2026-05-01T15:30:00'),
  },
  {
    id: 'bk-006',
    classId: 'cls-007',
    className: 'Pranayama & Meditación',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.b@email.com',
    persons: 2,
    upsells: [],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260507-K1L2',
    createdAt: new Date('2026-05-01T16:00:00'),
  },
  {
    id: 'bk-007',
    classId: 'cls-004',
    className: 'Yin Yoga',
    firstName: 'Emma',
    lastName: 'García',
    email: 'emma.garcia@email.com',
    persons: 1,
    upsells: [],
    paymentStatus: 'pending',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260505-M3N4',
    createdAt: new Date('2026-05-02T11:20:00'),
  },
  {
    id: 'bk-008',
    classId: 'cls-008',
    className: 'Restorative Yoga',
    firstName: 'Valentina',
    lastName: 'López',
    email: 'v.lopez@email.com',
    phone: '+54 9-11-1234-5678',
    persons: 1,
    upsells: ['ups-002'],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260507-O5P6',
    createdAt: new Date('2026-04-30T20:15:00'),
  },
  {
    id: 'bk-009',
    classId: 'cls-009',
    className: 'Sunrise Vinyasa',
    firstName: 'Thomas',
    lastName: 'Müller',
    email: 't.muller@email.com',
    persons: 1,
    upsells: [],
    paymentStatus: 'cancelled',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260508-Q7R8',
    createdAt: new Date('2026-05-01T08:00:00'),
  },
  {
    id: 'bk-010',
    classId: 'cls-005',
    className: 'Power Flow',
    firstName: 'Isabella',
    lastName: 'Martínez',
    email: 'isa.martinez@email.com',
    phone: '+52 55-1234-5678',
    persons: 2,
    upsells: ['ups-001'],
    paymentStatus: 'paid',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260506-S9T0',
    createdAt: new Date('2026-04-29T13:45:00'),
  },
  {
    id: 'bk-011',
    classId: 'cls-006',
    className: 'Hatha Foundations',
    firstName: 'Carlos',
    lastName: 'Herrera',
    email: 'carlos.h@email.com',
    persons: 1,
    upsells: [],
    paymentStatus: 'no-show',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260506-T1U2',
    createdAt: new Date('2026-04-30T09:00:00'),
  },
  {
    id: 'bk-012',
    classId: 'cls-002',
    className: 'Gentle Flow',
    firstName: 'Natalia',
    lastName: 'Soto',
    email: 'n.soto@email.com',
    persons: 3,
    upsells: ['ups-003'],
    paymentStatus: 'free',
    paymentMethod: 'card',
    totalUsd: 20,
    bookingReference: 'HOS-20260504-V3W4',
    createdAt: new Date('2026-05-02T20:00:00'),
  },
];

export const MOCK_UPSELLS: Upsell[] = [
  {
    id: 'ups-001',
    name: 'Mat de Yoga Premium',
    description: 'Alquiler de mat antideslizante de 6mm con toalla de microfibra incluida.',
    priceUsd: 5,
    isActive: true,
  },
  {
    id: 'ups-002',
    name: 'Té Ayurvédico Post-Clase',
    description: 'Selección de tés orgánicos elaborados con hierbas locales. Servido en el jardín.',
    priceUsd: 4,
    isActive: true,
  },
  {
    id: 'ups-003',
    name: 'Jugo Verde Detox',
    description: 'Jugo prensado en frío con ingredientes de la huerta orgánica de House of Shakti.',
    priceUsd: 8,
    isActive: true,
  },
  {
    id: 'ups-004',
    name: 'Sesión Privada 30 min',
    description: 'Consulta privada de 30 minutos con el instructor antes o después de la clase grupal.',
    priceUsd: 35,
    isActive: false,
  },
];

export const MOCK_REFERRAL_CODES: ReferralCode[] = [
  {
    id: 'ref-001',
    code: 'SURF-CAMP',
    partnerName: 'Nosara Surf Camp',
    description: '20% de descuento para clientes del Nosara Surf Camp.',
    benefitType: 'percentage',
    discountPercent: 20,
    isActive: true,
    usageLimit: 50,
    usageCount: 14,
    validFrom: new Date('2026-01-01'),
    validUntil: new Date('2026-12-31'),
    minPurchaseUsd: 0,
    createdAt: new Date('2025-12-15'),
  },
  {
    id: 'ref-002',
    code: 'HOTEL-PARTNER',
    partnerName: 'Hotel Tropicana',
    description: '$5 de descuento fijo para huéspedes del Hotel Tropicana.',
    benefitType: 'fixed',
    discountFixed: 5,
    isActive: true,
    usageLimit: undefined,
    usageCount: 31,
    validFrom: new Date('2026-01-01'),
    validUntil: undefined,
    minPurchaseUsd: 15,
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'ref-003',
    code: 'INSTAGRAM',
    partnerName: 'House of Shakti IG',
    description: '10% off para seguidores de Instagram que mencionen la cuenta.',
    benefitType: 'percentage',
    discountPercent: 10,
    isActive: true,
    usageLimit: undefined,
    usageCount: 58,
    validFrom: undefined,
    validUntil: undefined,
    minPurchaseUsd: 0,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 'ref-004',
    code: 'WELLNESS25',
    partnerName: 'Wellness Convention CR',
    description: '25% descuento especial para asistentes al congreso de bienestar.',
    benefitType: 'percentage',
    discountPercent: 25,
    isActive: false,
    usageLimit: 100,
    usageCount: 82,
    validFrom: new Date('2026-03-01'),
    validUntil: new Date('2026-04-30'),
    minPurchaseUsd: 20,
    createdAt: new Date('2026-02-20'),
  },
  {
    id: 'ref-005',
    code: 'MAT-FREE',
    partnerName: 'Temporada Baja',
    description: 'Mat Premium gratis al reservar cualquier clase en temporada baja.',
    benefitType: 'free_upsell',
    freeUpsellId: 'ups-001',
    isActive: true,
    usageLimit: 30,
    usageCount: 7,
    validFrom: new Date('2026-05-01'),
    validUntil: new Date('2026-07-31'),
    minPurchaseUsd: 0,
    createdAt: new Date('2026-04-28'),
  },
];

// Datos determinísticos para gráficos (evita problemas de hidratación)
function seededValue(day: number, max: number, min = 1): number {
  return Math.abs(((day * 1237 + 4321) % (max - min + 1)) + min);
}

export function getDailyBookingsData() {
  return Array.from({ length: 30 }, (_, i) => {
    const date = subDays(new Date('2026-05-04'), 29 - i);
    return {
      date: format(date, 'd MMM'),
      reservas: seededValue(i, 9, 1),
    };
  });
}

export function getWeeklyRevenueData() {
  return Array.from({ length: 8 }, (_, i) => {
    const weekNum = 8 - i;
    return {
      semana: `S${weekNum}`,
      ingresos: seededValue(i * 7, 480, 120),
    };
  });
}

export function getClassDistributionData() {
  return [
    { name: 'Sunrise Vinyasa', value: 28, color: CLASS_COLORS['Sunrise Vinyasa'] },
    { name: 'Ashtanga Primary', value: 18, color: CLASS_COLORS['Ashtanga Primary'] },
    { name: 'Yin Yoga', value: 15, color: CLASS_COLORS['Yin Yoga'] },
    { name: 'Gentle Flow', value: 14, color: CLASS_COLORS['Gentle Flow'] },
    { name: 'Otras', value: 25, color: '#94a3b8' },
  ];
}
